[tool.poetry]
name = "tptp-lark-parser"
version = "0.1.0"
description = "A TPTP parser using Lark"
authors = ["Boris Shminke <boris@shminke.ml>"]
license = "Apache-2.0"
repository = "https://github.com/inpefess/tptp-lark-parser"
readme = "README.rst"
classifiers=[
	"Programming Language :: Python :: 3.7",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"License :: OSI Approved :: Apache Software License",
	"Operating System :: OS Independent",
	"Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Mathematics",
	"Development Status :: 3 - Alpha",
	"Environment :: Console",
	"Natural Language :: English",
	"Typing :: Typed"
]
include = ["tptp_lark_parser/py.typed"]

[tool.poetry.dependencies]
python = ">= 3.7.1, < 3.12"
lark-parser = "*"
importlib_resources = {version = "*", markers = "python_version < \"3.9\""}

[tool.poetry.dev-dependencies]
black = "*"
jupyterlab = "*"
mypy = "*"
pylint = "*"
pytest-coverage = "*"
pre-commit = "*"
types-dataclasses = "*"
sphinx-rtd-theme = "*"
sphinx-autodoc-typehints = "*"
flake8 = "*"
pydocstyle = "*"
pyenchant = "*"
tbump = "*"

[tool.black]
line-length=79

[tool.isort]
profile = "black"
src_paths = ["tptp_lark_parser"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--doctest-modules --cov tptp_lark_parser --cov-report term-missing --cov-report xml --cov-fail-under=100 --junit-xml test-results/tptp-lark-parser.xml"
testpaths = ["tptp_lark_parser"]
doctest_optionflags = "NORMALIZE_WHITESPACE ELLIPSIS"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "from importlib.resources import files"
]

[tool.pylint.MASTER]
load-plugins = ["pylint.extensions.docparams"]

[tool.pylint.parameter_documentation]
accept-no-param-doc = false
accept-no-raise-doc = false
accept-no-return-doc = true
accept-no-yields-doc = false
default-docstring-type = "sphinx"

[tool.pylint.spelling]
spelling-dict = "en_GB"
spelling-private-dict-file = "spelling.dict"

[tool.pylint.format]
ignore-long-lines = "(::=|:==|this_is_a_test_case|:math:|.. math::|https://)"
max-line-length = 79

[tool.pylint.design]
max-statements = 10

[tool.mypy]
show_error_codes = true
incremental = true
disable_error_code = "no-redef"

[[tool.mypy.overrides]]
module = ["importlib_resources"]
ignore_missing_imports = true

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = True
envlist = py37,py38,py39,py310,py311

[testenv]
deps =
    pytest-cov
    pydocstyle
    flake8
    pylint
    mypy
    toml
    pyenchant
commands =
    pydocstyle tptp_lark_parser
    flake8 tptp_lark_parser
    pylint tptp_lark_parser
    mypy tptp_lark_parser
    pytest
"""

[tool.tbump]
github_url = "https://github.com/inpfess/tptp-lark-parser/"

[tool.tbump.version]
current = "0.1.0"
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.file]]
src = "tptp_lark_parser/__init__.py"

[[tool.tbump.file]]
src = "pyproject.toml"

[[tool.tbump.file]]
src = "doc/source/conf.py"
